---
- name: reload docker via systemd
  systemd:
    name: docker
    state: reloaded
  listen: reload docker

- name: restart service docker
  service:
    name: docker
    state: restarted
  when: docker_live_restore
  listen: reload docker
