---
- name: install packages for docker
  apt:
    name:
      - '{{ docker_apt_package }}'
      - python3-docker
    state: present

- name: enable service docker at system boot
  systemd:
    name: docker
    enabled: 'yes'
    masked: 'no'
    daemon_reload: true

- name: configure docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: reload docker

- name: set sysctl vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
  when: vm_max_map_count
